language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- ./internal/scripts/support/setup.sh && pip install github3.py
script:
- make build_for_gh_pages
- ./internal/scripts/support/upload_to_csplib-builds.sh
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
  - secure: "LsVKLWRl0VA9BqRz/H96tHTYRWV6ejFSyFN6JF4QoatZdv8kpBbblDGTXw2e+DdSn/prQCvxg26Vw4GxvFsxy+xH+/XXwTQPntSQUUCBNUpkUN/FqdvpMVVIxh5N9c57EhTuKRcoYjyhE+a5UgdMSdRGw86WGrsF7hsfilYvK2M="
